import type { Galaxy } from '../types';

/**
 * Exports the galaxy as a study guide: one chapter per constellation (largest first),
 * its keywords, and its ideas in the order they appear in the original document.
 */
export function studyGuideMarkdown(g: Galaxy, mastered: Set<number>) {
  const minutes = Math.max(1, Math.round(g.words / 230));
  const out = [
    `# ${g.title}: study guide`,
    '',
    `> Generated by [Constellate](https://constellate-black.vercel.app) on your device. ${g.words.toLocaleString()} words (≈${minutes} min read) organised into ${g.stars.length} ideas and ${g.constellations.length} topics.`,
    g.source ? `> Source: ${g.source}` : '',
    '',
    '## Topics at a glance',
    '',
    ...[...g.constellations].sort((a, b) => b.size - a.size).map((c, i) => `${i + 1}. **${c.name}**: ${c.size} ideas · _${c.keywords.join(', ')}_`),
    '',
  ];
  for (const c of [...g.constellations].sort((a, b) => b.size - a.size)) {
    out.push(`## ${c.name}`, '', `Key terms: ${c.keywords.map((k) => `\`${k}\``).join(' ')}`, '');
    for (const s of g.stars.filter((s) => s.cluster === c.id)) {
      out.push(`- [${mastered.has(s.id) ? 'x' : ' '}] ${s.text}${s.section ? ` _(§ ${s.section})_` : ''}`);
    }
    out.push('');
  }
  return out.filter((l, i, a) => !(l === '' && a[i - 1] === '')).join('\n');
}

export function downloadStudyGuide(g: Galaxy, mastered: Set<number>) {
  const blob = new Blob([studyGuideMarkdown(g, mastered)], { type: 'text/markdown' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${g.title.toLowerCase().replace(/\W+/g, '-')}-study-guide.md`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 1000);
}
